CREATE TABLE `ic_cat_tc_cuenta_contable` (
  `id_cuenta_contable` int(11) NOT NULL AUTO_INCREMENT,
  `id_grupo_empresa` int(11) NOT NULL,
  `id_sucursal` int(11) DEFAULT NULL,
  `anio` varchar(4) DEFAULT NULL,
  `mes` varchar(4) DEFAULT NULL,
  `num_cuenta` varchar(20) DEFAULT NULL,
  `tipo_cuenta` varchar(1) DEFAULT NULL,
  `nom_cuenta` varchar(50) DEFAULT NULL,
  `saldo_inicial` double DEFAULT NULL,
  `cargos` double DEFAULT NULL,
  `saldo_final` double DEFAULT NULL,
  `nivel` int(11) DEFAULT NULL,
  `escxp` int(11) DEFAULT NULL,
  `descripcion` varchar(255) DEFAULT NULL,
  `estatus` enum('ACTIVO','INACTIVO') DEFAULT 'ACTIVO',
  `fecha_mod` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_cuenta_contable`),
  KEY `fk_empresa_cuenta_cont_idx` (`id_grupo_empresa`),
  KEY `fk_sucursal_cuenta_cont_idx` (`id_sucursal`),
  KEY `idx_num_cuenta` (`num_cuenta`),
  KEY `idx_nom_cuenta` (`nom_cuenta`),
  CONSTRAINT `fk_empresa_cuenta_cont` FOREIGN KEY (`id_grupo_empresa`) REFERENCES `suite_mig_conf`.`st_adm_tr_grupo_empresa` (`id_grupo_empresa`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_sucursal_cuenta_cont` FOREIGN KEY (`id_sucursal`) REFERENCES `ic_cat_tr_sucursal` (`id_sucursal`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=120 DEFAULT CHARSET=utf8;
