CREATE TABLE `ic_cat_tr_cliente` (
  `id_cliente` int(11) NOT NULL AUTO_INCREMENT,
  `id_grupo_empresa` int(11) NOT NULL,
  `id_sucursal` int(11) NOT NULL,
  `id_corporativo` int(11) DEFAULT NULL,
  `id_vendedor` int(11) DEFAULT NULL,
  `id_direccion` int(11) DEFAULT NULL,
  `id_cuenta_contable` int(11) DEFAULT NULL,
  `rfc` varchar(20) DEFAULT NULL,
  `cve_cliente` varchar(45) DEFAULT NULL,
  `razon_social` varchar(255) DEFAULT NULL,
  `tipo_persona` char(1) DEFAULT NULL,
  `nombre_comercial` varchar(255) DEFAULT NULL,
  `tipo_cliente` enum('EVENTUAL','FIJO') DEFAULT NULL,
  `telefono` varchar(15) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `cve_gds` varchar(10) DEFAULT NULL,
  `datos_adicionales` int(11) DEFAULT NULL,
  `cuenta_pagos_fe` varchar(255) DEFAULT NULL,
  `enviar_mail_boleto` char(1) DEFAULT NULL,
  `facturar_boleto` char(1) DEFAULT NULL,
  `facturar_boleto_automatico` char(1) DEFAULT NULL,
  `observaciones` varchar(55) DEFAULT NULL,
  `notas_factura` varchar(255) DEFAULT NULL,
  `envio_cfdi_portal` char(1) DEFAULT NULL,
  `dias_credito` int(11) DEFAULT NULL,
  `limite_credito` decimal(15,2) DEFAULT NULL,
  `saldo` decimal(15,2) DEFAULT '0.00',
  `complemento_ine` char(1) DEFAULT '0',
  `fp_credito_agencia` char(1) DEFAULT 'N',
  `fp_contado` char(1) DEFAULT 'S',
  `fp_tc_cliente` char(1) DEFAULT 'S',
  `gr_credito_agencia` char(1) DEFAULT 'N',
  `gr_contado` char(1) DEFAULT 'S',
  `gr_tc_agencia` char(1) DEFAULT 'N',
  `gr_tc_cliente` char(1) DEFAULT 'S',
  `fecha_creacion` datetime DEFAULT NULL,
  `estatus` enum('ACTIVO','INACTIVO') DEFAULT 'ACTIVO',
  `fecha_mod` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `id_usuario` int(11) DEFAULT NULL,
  PRIMARY KEY (`id_cliente`),
  KEY `fk_sucursal_idx` (`id_sucursal`),
  KEY `fk_corporativo_idx` (`id_corporativo`),
  KEY `fk_vendedor_idx` (`id_vendedor`),
  KEY `fk_dir_cliente_idx` (`id_direccion`),
  KEY `fk_idx` (`id_usuario`),
  KEY `fk_cliente_grupo_empresa_idx` (`id_grupo_empresa`),
  KEY `fk_cliente_idx` (`id_cuenta_contable`),
  CONSTRAINT `fk_cliente` FOREIGN KEY (`id_cuenta_contable`) REFERENCES `ic_cat_tc_cuenta_contable` (`id_cuenta_contable`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_grupo_empresa` FOREIGN KEY (`id_grupo_empresa`) REFERENCES `suite_mig_conf`.`st_adm_tr_grupo_empresa` (`id_grupo_empresa`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_usuario` FOREIGN KEY (`id_usuario`) REFERENCES `suite_mig_conf`.`st_adm_tr_usuario` (`id_usuario`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_corporativo` FOREIGN KEY (`id_corporativo`) REFERENCES `ic_cat_tr_corporativo` (`id_corporativo`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_dir_cliente` FOREIGN KEY (`id_direccion`) REFERENCES `ct_glob_tc_direccion` (`id_direccion`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_sucursal` FOREIGN KEY (`id_sucursal`) REFERENCES `ic_cat_tr_sucursal` (`id_sucursal`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendedor` FOREIGN KEY (`id_vendedor`) REFERENCES `ic_cat_tr_vendedor` (`id_vendedor`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=16113 DEFAULT CHARSET=utf8;
