CREATE TABLE `ic_cat_tr_proveedor` (
  `id_proveedor` int(11) NOT NULL AUTO_INCREMENT,
  `id_grupo_empresa` int(11) NOT NULL,
  `cve_proveedor` varchar(10) DEFAULT NULL,
  `id_tipo_proveedor` int(11) DEFAULT NULL,
  `id_direccion` int(11) DEFAULT NULL,
  `id_sucursal` int(11) DEFAULT NULL,
  `id_sat_tipo_tercero` int(11) DEFAULT NULL,
  `id_sat_tipo_operacion` int(11) DEFAULT NULL,
  `tipo_proveedor_operacion` enum('INGRESO','EGRESO','AMBOS') DEFAULT NULL,
  `tipo_persona` char(1) DEFAULT NULL,
  `rfc` varchar(30) DEFAULT NULL,
  `razon_social` varchar(255) DEFAULT NULL,
  `nombre_comercial` varchar(255) DEFAULT NULL,
  `telefono` varchar(45) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `concepto_pago` varchar(255) DEFAULT NULL,
  `porcentaje_prorrateo` char(1) DEFAULT NULL,
  `estatus` enum('ACTIVO','INACTIVO') DEFAULT 'ACTIVO',
  `fecha_mod` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `id_usuario` int(11) NOT NULL,
  PRIMARY KEY (`id_proveedor`),
  KEY `id_tipo_proveedor_idx` (`id_tipo_proveedor`) USING BTREE,
  KEY `ic_cat_tr_proveedor_ibfk_2` (`id_sucursal`) USING BTREE,
  KEY `ic_cat_tr_proveedor_ibfk_5` (`id_direccion`) USING BTREE,
  KEY `ic_cat_tr_proveedor_ibfk_3` (`id_sat_tipo_tercero`) USING BTREE,
  KEY `ic_cat_tr_proveedor_ibfk_4` (`id_sat_tipo_operacion`) USING BTREE,
  KEY `fk_proveedor_usuario_idx` (`id_usuario`) USING BTREE,
  KEY `fk_proveedor_grupo_empresa_idx` (`id_grupo_empresa`) USING BTREE,
  KEY `idx_cve_proveedor` (`cve_proveedor`) USING BTREE,
  CONSTRAINT `fk_proveedor_grupo_empresa` FOREIGN KEY (`id_grupo_empresa`) REFERENCES `suite_mig_conf`.`st_adm_tr_grupo_empresa` (`id_grupo_empresa`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_proveedor_usuario` FOREIGN KEY (`id_usuario`) REFERENCES `suite_mig_conf`.`st_adm_tr_usuario` (`id_usuario`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ic_cat_tr_proveedor_ibfk_1` FOREIGN KEY (`id_tipo_proveedor`) REFERENCES `ic_cat_tc_tipo_proveedor` (`id_tipo_proveedor`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ic_cat_tr_proveedor_ibfk_2` FOREIGN KEY (`id_sucursal`) REFERENCES `ic_cat_tr_sucursal` (`id_sucursal`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ic_cat_tr_proveedor_ibfk_3` FOREIGN KEY (`id_sat_tipo_tercero`) REFERENCES `ic_glob_tc_tipo_tercero_sat` (`id_sat_tipo_tercero`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ic_cat_tr_proveedor_ibfk_4` FOREIGN KEY (`id_sat_tipo_operacion`) REFERENCES `ic_glob_tc_tipo_ope_sat` (`id_sat_tipo_operacion`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ic_cat_tr_proveedor_ibfk_5` FOREIGN KEY (`id_direccion`) REFERENCES `ct_glob_tc_direccion` (`id_direccion`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3293 DEFAULT CHARSET=utf8;
