CREATE TABLE `ic_cat_tc_servicio` (
  `id_servicio` int(11) NOT NULL AUTO_INCREMENT,
  `id_grupo_empresa` int(11) DEFAULT NULL,
  `id_producto` int(11) DEFAULT NULL,
  `id_unidad_medida` int(11) DEFAULT NULL,
  `c_ClaveProdServ` char(10) DEFAULT NULL,
  `cve_servicio` char(10) DEFAULT NULL,
  `alcance` enum('NACIONAL','INTERNACIONAL') DEFAULT NULL,
  `descripcion` varchar(100) DEFAULT NULL,
  `valida_adicis` enum('SI','NO') DEFAULT NULL,
  `estatus` enum('ACTIVO','INACTIVO') DEFAULT 'ACTIVO',
  `id_usuario` int(11) NOT NULL,
  `fecha_mod` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_servicio`),
  KEY `idx_cve_servicio` (`cve_servicio`) USING BTREE,
  KEY `ic_cat_tc_servicio_ibfk_1_idx` (`id_producto`) USING BTREE,
  KEY `fk_servicio_usuario_idx` (`id_usuario`) USING BTREE,
  KEY `fk_empresa_servicio_idx` (`id_grupo_empresa`) USING BTREE,
  KEY `fk_servicio_unidad_idx` (`id_unidad_medida`) USING BTREE,
  KEY `idx_c_ClaveProdServ` (`c_ClaveProdServ`) USING BTREE,
  CONSTRAINT `fk_empresa_servicio` FOREIGN KEY (`id_grupo_empresa`) REFERENCES `suite_mig_conf`.`st_adm_tr_grupo_empresa` (`id_grupo_empresa`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicio_unidad` FOREIGN KEY (`id_unidad_medida`) REFERENCES `ic_cat_tc_unidad_medida` (`id_unidad_medida`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicio_usuario` FOREIGN KEY (`id_usuario`) REFERENCES `suite_mig_conf`.`st_adm_tr_usuario` (`id_usuario`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ic_cat_tc_servicio_ibfk_1` FOREIGN KEY (`id_producto`) REFERENCES `ic_cat_tc_producto` (`id_producto`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=576 DEFAULT CHARSET=utf8;
