CREATE TABLE `ic_fac_tr_anticipos` (
  `id_anticipos` int(11) NOT NULL AUTO_INCREMENT,
  `id_grupo_empresa` int(11) NOT NULL,
  `id_factura` int(11) DEFAULT NULL,
  `id_cliente` int(11) NOT NULL,
  `anticipo_moneda_facturada` decimal(13,2) DEFAULT NULL,
  `anticipo_moneda_base` decimal(13,2) DEFAULT NULL,
  `tipo_cambio` decimal(13,4) DEFAULT NULL,
  `fecha` date DEFAULT NULL,
  `importe_aplicado_moneda_facturada` decimal(13,2) DEFAULT NULL,
  `importe_aplicado_base` decimal(13,2) DEFAULT NULL,
  `anticipo_usd` decimal(13,2) DEFAULT NULL,
  `anticipo_eur` decimal(13,2) DEFAULT NULL,
  `importe_aplicado_usd` decimal(13,2) DEFAULT '0.00',
  `importe_aplicado_eur` decimal(13,2) DEFAULT '0.00',
  `id_grupo_fit` int(11) DEFAULT NULL,
  `id_moneda` int(11) NOT NULL,
  `estatus` enum('ACTIVO','CANCELADA') DEFAULT 'ACTIVO',
  `id_usuario` int(11) DEFAULT NULL,
  `fecha_mod` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_anticipos`),
  KEY `fk_anticipo_grupo_empresa_idx` (`id_grupo_empresa`),
  KEY `fk_anticipo_factura_idx` (`id_factura`),
  KEY `fk_anticipo_cliente_idx` (`id_cliente`),
  KEY `fk_anticipo_moneda_idx` (`id_moneda`),
  KEY `fk_anticipo_usuario_idx` (`id_usuario`),
  CONSTRAINT `fk_anticipo_cliente` FOREIGN KEY (`id_cliente`) REFERENCES `ic_cat_tr_cliente` (`id_cliente`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_anticipo_factura` FOREIGN KEY (`id_factura`) REFERENCES `ic_fac_tr_factura` (`id_factura`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_anticipo_grupo_empresa` FOREIGN KEY (`id_grupo_empresa`) REFERENCES `suite_mig_conf`.`st_adm_tr_grupo_empresa` (`id_grupo_empresa`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_anticipo_moneda` FOREIGN KEY (`id_moneda`) REFERENCES `ct_glob_tc_moneda` (`id_moneda`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_anticipo_usuario` FOREIGN KEY (`id_usuario`) REFERENCES `suite_mig_conf`.`st_adm_tr_usuario` (`id_usuario`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=166 DEFAULT CHARSET=latin1;
