CREATE TABLE `ic_fac_tr_factura_detalle` (
  `id_factura_detalle` int(11) NOT NULL AUTO_INCREMENT,
  `id_factura` int(11) DEFAULT NULL,
  `id_prov_tpo_serv` int(11) DEFAULT NULL,
  `id_boleto` int(11) DEFAULT NULL,
  `id_factura_cxs` int(11) DEFAULT NULL,
  `id_grupo_fit` char(10) DEFAULT NULL,
  `id_proveedor` int(11) DEFAULT NULL,
  `id_servicio` int(11) DEFAULT NULL,
  `clave_prod_serv_sat` char(15) DEFAULT NULL,
  `clave_prod_serv_desc_sat` varchar(100) DEFAULT NULL,
  `numero_boleto` varchar(15) DEFAULT NULL,
  `concepto` varchar(250) DEFAULT NULL,
  `nombre_pasajero` varchar(30) DEFAULT NULL,
  `tarifa_moneda_base` decimal(15,2) DEFAULT NULL,
  `tarifa_moneda_facturada` decimal(16,2) DEFAULT NULL,
  `comision_agencia` decimal(15,2) DEFAULT NULL,
  `porc_comision_agencia` decimal(5,2) DEFAULT NULL,
  `descuento` decimal(15,2) DEFAULT NULL,
  `comision_titular` decimal(15,2) DEFAULT NULL,
  `porc_comision_titular` decimal(5,2) DEFAULT NULL,
  `comision_auxiliar` decimal(15,2) DEFAULT NULL,
  `porc_comision_auxiliar` decimal(5,2) DEFAULT NULL,
  `suma_impuestos` decimal(15,2) DEFAULT NULL,
  `iva_comision` decimal(15,2) DEFAULT NULL,
  `porc_iva_comision` decimal(5,2) DEFAULT NULL,
  `boleto_contra` char(1) DEFAULT NULL,
  `la_contra` char(2) DEFAULT NULL,
  `numero_boleto_contra` varchar(15) DEFAULT NULL,
  `boleto_conjunto` char(1) DEFAULT NULL,
  `id_prov_num_cta` int(11) DEFAULT NULL,
  `id_prov_num_cta_resul` int(11) DEFAULT NULL,
  `porc_descuento` decimal(5,2) DEFAULT NULL,
  `iva_descuento` decimal(15,2) DEFAULT NULL,
  `importe_credito` decimal(15,2) DEFAULT NULL,
  `numero_tarjeta` varchar(100) DEFAULT NULL,
  `referencia_cxp` char(15) DEFAULT NULL,
  `numero_bol_cxs` char(15) DEFAULT NULL,
  `bol_electronico` int(11) DEFAULT NULL,
  `id_regla` varchar(10) DEFAULT NULL,
  `comision_cedida` decimal(8,2) DEFAULT NULL,
  `clave_reservacion` varchar(10) DEFAULT NULL,
  `boleto_facturado` char(1) DEFAULT NULL COMMENT 'Facturación de Aeromexico',
  `facturar_agencia` char(1) DEFAULT NULL,
  `emd` char(1) DEFAULT NULL,
  `importe_markup` decimal(15,2) DEFAULT NULL,
  `porc_markup` decimal(5,2) DEFAULT NULL,
  `num_servicios` int(11) DEFAULT NULL,
  `id_unidad_medida` int(11) DEFAULT NULL,
  `clave_unidad_sat` char(4) DEFAULT NULL,
  `cuenta_ingreso` varchar(20) DEFAULT NULL,
  `cuenta_ingreso_porcentaje` decimal(5,2) DEFAULT NULL,
  `impuesto_x_pagar` decimal(16,6) DEFAULT NULL,
  `cantidad` int(11) DEFAULT '1',
  `fecha_mod` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `nc_tipo_remb` enum('CREDITO','EFECTIVO') DEFAULT NULL,
  `nc_rembolso` enum('SI','NO') DEFAULT NULL,
  `complemento_terceros` char(1) DEFAULT NULL,
  `id_usuario` int(11) DEFAULT NULL,
  PRIMARY KEY (`id_factura_detalle`),
  KEY `fk_detalle_servicio_idx` (`id_servicio`) USING BTREE,
  KEY `fk_detalle_proveedor_idx` (`id_proveedor`) USING BTREE,
  KEY `fk_factura_detalle_usuario_idx` (`id_usuario`),
  KEY `fk_detalle_factura_idx` (`id_factura`),
  CONSTRAINT `fk_detalle_factura` FOREIGN KEY (`id_factura`) REFERENCES `ic_fac_tr_factura` (`id_factura`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_proveedor` FOREIGN KEY (`id_proveedor`) REFERENCES `ic_cat_tr_proveedor` (`id_proveedor`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_detalle_servicio` FOREIGN KEY (`id_servicio`) REFERENCES `ic_cat_tc_servicio` (`id_servicio`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_factura_detalle_usuario` FOREIGN KEY (`id_usuario`) REFERENCES `suite_mig_conf`.`st_adm_tr_usuario` (`id_usuario`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=7443 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
