CREATE TABLE `ic_fac_tr_pagos_cfdi` (
  `id_cfdi` int(11) NOT NULL AUTO_INCREMENT,
  `id_pago` int(11) DEFAULT NULL,
  `numero_certificado` varchar(20) CHARACTER SET utf8 DEFAULT NULL,
  `cadena_original` text CHARACTER SET utf8,
  `sello_digital` text CHARACTER SET utf8,
  `certificado` text CHARACTER SET utf8,
  `genera_xml` char(1) CHARACTER SET utf8 DEFAULT 'N',
  `factura_xml` blob,
  `genera_pdf` char(1) CHARACTER SET utf8 DEFAULT 'N',
  `fecha_envio_email` datetime DEFAULT NULL,
  `timbre_cfdi` text CHARACTER SET utf8,
  `version_timbrado` varchar(4) CHARACTER SET utf8 DEFAULT NULL,
  `uuid` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
  `fecha_timbrado` datetime DEFAULT NULL,
  `numero_certificado_sat` varchar(20) CHARACTER SET utf8 DEFAULT NULL,
  `sello_sat` text CHARACTER SET utf8,
  `cadena_timbre` text CHARACTER SET utf8,
  `cfdi_timbrado` char(1) CHARACTER SET utf8 DEFAULT NULL,
  `confirma_cancelacion_cfdi` text CHARACTER SET utf8,
  `archivo_addenda` text CHARACTER SET utf8,
  `rfc_prov_ser` varchar(45) CHARACTER SET utf8 DEFAULT NULL,
  PRIMARY KEY (`id_cfdi`),
  KEY `fk_cfdi_pago_idx` (`id_pago`)
) ENGINE=InnoDB AUTO_INCREMENT=818 DEFAULT CHARSET=utf8mb4;
