CREATE TABLE `ic_fac_tr_pagos` (
  `id_pago` int(11) NOT NULL AUTO_INCREMENT,
  `id_grupo_empresa` int(11) DEFAULT NULL,
  `id_sucursal` int(11) DEFAULT NULL,
  `id_serie` int(11) DEFAULT NULL,
  `id_cliente` int(11) DEFAULT NULL,
  `id_moneda` int(11) DEFAULT NULL,
  `id_direccion` int(11) DEFAULT NULL,
  `id_usuario` int(11) DEFAULT NULL,
  `id_forma_pago` int(11) DEFAULT NULL,
  `id_pago_sustituye_a` int(11) DEFAULT NULL,
  `id_pago_sustituido_por` int(11) DEFAULT NULL,
  `numero` int(13) DEFAULT NULL,
  `razon_social` varchar(255) DEFAULT NULL,
  `rfc` varchar(20) DEFAULT NULL,
  `fecha` date DEFAULT NULL,
  `fecha_captura_recibo` date DEFAULT NULL,
  `tpo_cambio` decimal(10,4) DEFAULT NULL,
  `total_pago` decimal(13,2) DEFAULT NULL,
  `total_pago_moneda_base` decimal(13,2) DEFAULT NULL,
  `mtvo_cancelacion` varchar(255) DEFAULT NULL,
  `aplica_contab` int(11) DEFAULT NULL,
  `fecha_cancelacion` date DEFAULT NULL,
  `hora_cancelacion` time DEFAULT NULL,
  `mail_cliente` varchar(255) DEFAULT NULL,
  `envio_electronico` char(1) DEFAULT NULL,
  `c_UsoCFDI_sat` char(4) DEFAULT NULL,
  `c_Formapago` char(4) DEFAULT NULL,
  `c_UsoCFDI_descripcion_sat` varchar(50) DEFAULT NULL,
  `no_operacion` varchar(50) DEFAULT NULL,
  `confirmacion_pac` char(5) DEFAULT NULL,
  `rfcemisorctaord` char(12) DEFAULT NULL,
  `nombancoordext` varchar(300) DEFAULT NULL,
  `nombancoemisor` varchar(300) DEFAULT NULL,
  `ctaordenante` varchar(50) DEFAULT NULL,
  `rfcemisorctaben` char(12) DEFAULT NULL,
  `ctabeneficiario` varchar(50) DEFAULT NULL,
  `tipocadpago` char(2) DEFAULT NULL,
  `certpago` varchar(300) DEFAULT NULL,
  `cadpago` varchar(300) DEFAULT NULL,
  `estatus` enum('ACTIVO','CANCELADO') DEFAULT 'ACTIVO',
  `fecha_mod` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `concepto_p` varchar(200) DEFAULT NULL,
  `concepto_c` varchar(200) DEFAULT NULL,
  `recibimos_de` varchar(200) DEFAULT NULL,
  `sello_spei` text,
  `tipo_cambio_usd` decimal(15,4) DEFAULT NULL,
  `tipo_cambio_eur` decimal(15,4) DEFAULT NULL,
  `id_razon_cancelacion` int(11) DEFAULT NULL,
  `id_usuario_cancelacion` int(11) DEFAULT NULL,
  `id_estatus_cancelacion` int(11) DEFAULT NULL,
  `fecha_solicitud_cancelacion` date DEFAULT NULL,
  `hora_solicitud_cancelacion` time DEFAULT NULL,
  `factura_pdf` mediumblob,
  PRIMARY KEY (`id_pago`),
  KEY `fk_pagos_grupo_empresa_idx` (`id_grupo_empresa`),
  KEY `fk_pagos_sucursal_idx` (`id_sucursal`),
  KEY `fk_pagos_serie_idx` (`id_serie`),
  KEY `fk_pagos_cliente_idx` (`id_cliente`),
  KEY `fk_pagos_monedas_idx` (`id_moneda`),
  KEY `fk_pagos_direccion_idx` (`id_direccion`),
  KEY `fk_pagos_usuario_idx` (`id_usuario`),
  KEY `fk_pagos_usuario_cancelacion_idx` (`id_usuario_cancelacion`),
  KEY `fk_pagos_estatus_cancelacion_idx` (`id_estatus_cancelacion`),
  CONSTRAINT `fk_pagos_cliente` FOREIGN KEY (`id_cliente`) REFERENCES `ic_cat_tr_cliente` (`id_cliente`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagos_direccion` FOREIGN KEY (`id_direccion`) REFERENCES `ct_glob_tc_direccion` (`id_direccion`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagos_estatus_cancelacion` FOREIGN KEY (`id_estatus_cancelacion`) REFERENCES `ic_fac_tc_factura_estatus_cancelacion` (`id_estatus_cancelacion`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagos_grupo_empresa` FOREIGN KEY (`id_grupo_empresa`) REFERENCES `suite_mig_conf`.`st_adm_tr_grupo_empresa` (`id_grupo_empresa`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagos_monedas` FOREIGN KEY (`id_moneda`) REFERENCES `ct_glob_tc_moneda` (`id_moneda`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagos_serie` FOREIGN KEY (`id_serie`) REFERENCES `ic_cat_tr_serie` (`id_serie`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagos_sucursal` FOREIGN KEY (`id_sucursal`) REFERENCES `ic_cat_tr_sucursal` (`id_sucursal`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagos_usuario` FOREIGN KEY (`id_usuario`) REFERENCES `suite_mig_conf`.`st_adm_tr_usuario` (`id_usuario`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagos_usuario_cancelacion` FOREIGN KEY (`id_usuario_cancelacion`) REFERENCES `suite_mig_conf`.`st_adm_tr_usuario` (`id_usuario`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=3927 DEFAULT CHARSET=utf8;
