CREATE TABLE `ic_glob_tr_cxp_pago_anticipo_proveedores` (
  `id_pago_anticipo_proveedores` int(11) NOT NULL AUTO_INCREMENT,
  `id_grupo_empresa` int(11) NOT NULL,
  `id_cxp` int(11) DEFAULT NULL,
  `id_proveedor` int(11) NOT NULL,
  `id_serie` int(11) DEFAULT NULL,
  `id_sucursal` int(11) DEFAULT NULL,
  `numero` int(11) DEFAULT NULL,
  `referencia_pago` varchar(255) DEFAULT NULL,
  `tipo_pago` enum('PAGO','ANTICIPO') DEFAULT NULL,
  `id_moneda` int(11) DEFAULT NULL,
  `tipo_cambio` decimal(15,4) DEFAULT NULL,
  `importe_pago` decimal(16,2) DEFAULT '0.00',
  `total_pago` decimal(16,2) DEFAULT '0.00',
  `importe_anticipos` decimal(16,2) DEFAULT '0.00',
  `importe_pago_mn` decimal(16,2) DEFAULT '0.00',
  `total_pago_mn` decimal(16,2) DEFAULT '0.00',
  `importe_anticipos_mn` decimal(16,2) DEFAULT '0.00',
  `importe_usd` decimal(17,4) DEFAULT '0.0000',
  `tipo_cambio_usd` decimal(15,4) DEFAULT '0.0000',
  `importe_eur` decimal(17,4) DEFAULT '0.0000',
  `tipo_cambio_eur` decimal(15,4) DEFAULT '0.0000',
  `fecha_pago` date DEFAULT NULL,
  `id_banco_emisor` int(11) DEFAULT NULL,
  `rfc_banco_emisor` varchar(16) DEFAULT NULL,
  `numero_cuenta_emisor` varchar(20) DEFAULT NULL,
  `id_banco_proveedor` int(11) DEFAULT NULL,
  `CLABE_interbancaria_proveedor` varchar(18) DEFAULT NULL,
  `numero_cuenta_proveedor` varchar(20) DEFAULT NULL,
  `id_metodo_pago` int(11) DEFAULT NULL,
  `forma_pago` char(1) DEFAULT NULL,
  `uuid` varchar(40) DEFAULT NULL,
  `pdf_pago_anticipo_proveedor` mediumblob,
  `id_motivo_cancelacion` int(11) DEFAULT NULL,
  `observaciones_cancelacion` varchar(250) DEFAULT NULL,
  `id_usuario_cancelacion` int(11) DEFAULT NULL,
  `fecha_cancelacion` date DEFAULT NULL,
  `hora_cancelacion` time DEFAULT NULL,
  `hora_pago` time DEFAULT NULL,
  `estatus` enum('ACTIVO','INACTIVO') DEFAULT 'ACTIVO',
  `situacion` enum('PENDIENTE','PAGADO','PROGRAMADO') DEFAULT 'PENDIENTE',
  `solicito` varchar(255) DEFAULT NULL,
  `fecha_mod` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `id_usuario` int(11) DEFAULT NULL,
  PRIMARY KEY (`id_pago_anticipo_proveedores`),
  KEY `fk_pago_anticipo_proveedor_usarios_idx` (`id_usuario`),
  KEY `fk_pago_anticipo_proveedor_cxp_idx` (`id_cxp`),
  KEY `fk_pago_anticipo_proveedores_proveedor_idx` (`id_proveedor`),
  KEY `fk_pago_anticipo_proveedor_serie_idx` (`id_serie`),
  KEY `fk_pago_anticipo_sucursal_idx` (`id_sucursal`),
  KEY `fk_pago_anticipo_usuario_cancelacion_idx` (`id_usuario_cancelacion`),
  KEY `fk_pago_anticipo_proveedor_grupo_empresa_idx` (`id_grupo_empresa`),
  KEY `fk_pago_forma_pago_banco_idx` (`id_banco_emisor`),
  KEY `fk_pago_forma_pago_banco_proveedor_idx` (`id_banco_proveedor`),
  CONSTRAINT `fk_pago_anticipo_proveedor_cxp` FOREIGN KEY (`id_cxp`) REFERENCES `ic_glob_tr_cxp` (`id_cxp`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_pago_anticipo_proveedor_grupo_empresa` FOREIGN KEY (`id_grupo_empresa`) REFERENCES `suite_mig_conf`.`st_adm_tr_grupo_empresa` (`id_grupo_empresa`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_pago_anticipo_proveedor_serie` FOREIGN KEY (`id_serie`) REFERENCES `ic_cat_tr_serie` (`id_serie`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_pago_anticipo_proveedor_usarios` FOREIGN KEY (`id_usuario`) REFERENCES `suite_mig_conf`.`st_adm_tr_usuario` (`id_usuario`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_pago_anticipo_proveedores_proveedor` FOREIGN KEY (`id_proveedor`) REFERENCES `ic_cat_tr_proveedor` (`id_proveedor`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_pago_anticipo_sucursal` FOREIGN KEY (`id_sucursal`) REFERENCES `ic_cat_tr_sucursal` (`id_sucursal`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_pago_anticipo_usuario_cancelacion` FOREIGN KEY (`id_usuario_cancelacion`) REFERENCES `suite_mig_conf`.`st_adm_tr_usuario` (`id_usuario`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_pago_forma_pago_banco_emisor` FOREIGN KEY (`id_banco_emisor`) REFERENCES `suite_mig_conf`.`st_adm_tr_config_banco` (`id_config_banco`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_pago_forma_pago_banco_proveedor` FOREIGN KEY (`id_banco_proveedor`) REFERENCES `ic_fac_tr_prove_cta_bancaria` (`id_prove_cta_bancaria`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=363 DEFAULT CHARSET=latin1;
