CREATE TABLE `ic_glob_tr_boleto` (
  `id_boletos` int(11) NOT NULL AUTO_INCREMENT,
  `id_grupo_empresa` int(11) DEFAULT NULL,
  `id_proveedor` int(11) DEFAULT NULL,
  `id_inventario` int(11) DEFAULT NULL,
  `id_gds` int(11) DEFAULT NULL,
  `id_sucursal` int(11) DEFAULT NULL,
  `id_factura_detalle` int(11) DEFAULT NULL,
  `origen` char(3) DEFAULT NULL,
  `numero_bol` varchar(15) DEFAULT NULL,
  `conjunto` varchar(15) DEFAULT NULL,
  `ruta` varchar(100) DEFAULT NULL,
  `estatus` enum('ACTIVO','INACTIVO','FACTURADO','CANCELADO') DEFAULT 'ACTIVO',
  `fecha_mod` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `id_usuario` int(11) DEFAULT NULL,
  `fecha_emision` date DEFAULT NULL,
  PRIMARY KEY (`id_boletos`),
  KEY `fk_boleto_inventario_idx` (`id_inventario`),
  KEY `fk_boleto_usuario_idx` (`id_usuario`),
  KEY `idx_numero_boleto` (`numero_bol`) USING BTREE,
  KEY `idx_id_boleto` (`id_boletos`) USING BTREE,
  KEY `fk_boleto_grupo_empresa_idx` (`id_grupo_empresa`),
  KEY `fk_boleto_proveedor_idx` (`id_proveedor`),
  KEY `fk_boleto_sucursal_idx` (`id_sucursal`),
  CONSTRAINT `fk_boleto_grupo_empresa` FOREIGN KEY (`id_grupo_empresa`) REFERENCES `suite_mig_conf`.`st_adm_tr_grupo_empresa` (`id_grupo_empresa`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_boleto_inventario` FOREIGN KEY (`id_inventario`) REFERENCES `ic_glob_tr_inventario_boletos` (`id_inventario_boletos`) ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT `fk_boleto_proovedor` FOREIGN KEY (`id_proveedor`) REFERENCES `ic_cat_tr_proveedor` (`id_proveedor`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_boleto_sucursal` FOREIGN KEY (`id_sucursal`) REFERENCES `ic_cat_tr_sucursal` (`id_sucursal`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_boleto_usuario` FOREIGN KEY (`id_usuario`) REFERENCES `suite_mig_conf`.`st_adm_tr_usuario` (`id_usuario`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=351543 DEFAULT CHARSET=utf8;
