CREATE TABLE `ic_glob_tr_cxc` (
  `id_cxc` int(11) NOT NULL AUTO_INCREMENT,
  `id_grupo_empresa` int(11) DEFAULT NULL,
  `id_sucursal` int(11) DEFAULT NULL,
  `id_factura` int(11) DEFAULT NULL,
  `id_poliza` int(11) DEFAULT NULL,
  `id_cliente` int(11) DEFAULT NULL,
  `id_vendedor` int(11) DEFAULT NULL,
  `id_moneda` int(11) DEFAULT NULL,
  `origen_documento` enum('Factura','Notas de Credito','Pólizas','Carga Inicial CxC','Documento de servicio') DEFAULT NULL,
  `importe_facturado` decimal(15,2) DEFAULT NULL,
  `pagos_facturado` decimal(15,2) DEFAULT NULL,
  `saldo_facturado` decimal(15,2) DEFAULT NULL,
  `importe_moneda_base` decimal(15,2) DEFAULT NULL,
  `pagos_moneda_base` decimal(15,2) DEFAULT NULL,
  `saldo_moneda_base` decimal(15,2) DEFAULT NULL,
  `tipo_cambio` decimal(17,4) DEFAULT NULL,
  `tipo_cambio_usd` decimal(17,4) DEFAULT NULL,
  `tipo_cambio_eur` decimal(17,4) DEFAULT NULL,
  `cve_serie` char(5) DEFAULT NULL,
  `fac_numero` int(13) DEFAULT NULL,
  `uuid` varchar(100) DEFAULT NULL,
  `fecha_emision` date DEFAULT NULL,
  `fecha_vencimiento` date DEFAULT NULL,
  `anterior_fecha_vencimiento` date DEFAULT NULL,
  `fecha_revision` date DEFAULT NULL,
  `anterior_fecha_revision` date DEFAULT NULL,
  `referencia_origen` varchar(50) DEFAULT NULL,
  `razon_social` varchar(255) DEFAULT NULL,
  `c_MetodoPago` char(3) DEFAULT NULL,
  `estatus` enum('ACTIVO','INACTIVO') DEFAULT 'ACTIVO',
  `fecha_mod` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `id_usuario` int(11) DEFAULT NULL,
  `cve_tipo_serie` char(4) DEFAULT NULL,
  PRIMARY KEY (`id_cxc`),
  KEY `fk_cxc_usuario_idx` (`id_usuario`),
  KEY `idx_serie_factura` (`cve_serie`,`fac_numero`),
  KEY `fk_cxc_grupo_empresa_idx` (`id_grupo_empresa`),
  KEY `fk_cxc_sucursal_idx` (`id_sucursal`),
  KEY `fk_cxc_cliente_idx` (`id_cliente`),
  KEY `fk_cxc_vendedor_idx` (`id_vendedor`),
  KEY `fk_cxc_moneda_idx` (`id_moneda`),
  KEY `fk_cxc_factura_idx` (`id_factura`),
  CONSTRAINT `fk_cxc_cliente` FOREIGN KEY (`id_cliente`) REFERENCES `ic_cat_tr_cliente` (`id_cliente`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_cxc_factura` FOREIGN KEY (`id_factura`) REFERENCES `ic_fac_tr_factura` (`id_factura`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_cxc_grupo_empresa` FOREIGN KEY (`id_grupo_empresa`) REFERENCES `suite_mig_conf`.`st_adm_tr_grupo_empresa` (`id_grupo_empresa`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_cxc_moneda` FOREIGN KEY (`id_moneda`) REFERENCES `ct_glob_tc_moneda` (`id_moneda`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_cxc_sucursal` FOREIGN KEY (`id_sucursal`) REFERENCES `ic_cat_tr_sucursal` (`id_sucursal`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_cxc_usuario` FOREIGN KEY (`id_usuario`) REFERENCES `suite_mig_conf`.`st_adm_tr_usuario` (`id_usuario`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_cxc_vendedor` FOREIGN KEY (`id_vendedor`) REFERENCES `ic_cat_tr_vendedor` (`id_vendedor`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=972371 DEFAULT CHARSET=utf8;
