CREATE TABLE `ic_gds_tr_autos` (
  `id_gds_autos` int(11) NOT NULL AUTO_INCREMENT,
  `id_factura_detalle` int(11) DEFAULT NULL,
  `id_arrendadora` int(11) DEFAULT NULL,
  `id_gds_general` int(11) DEFAULT NULL,
  `id_sucursal` int(11) DEFAULT NULL,
  `provedor` varchar(10) DEFAULT NULL,
  `numero_boleto` varchar(15) DEFAULT NULL,
  `serie` char(5) DEFAULT NULL,
  `fac_numero` int(11) DEFAULT NULL,
  `clave_reserva` varchar(20) DEFAULT NULL,
  `clave_confirmacion` varchar(20) DEFAULT NULL,
  `clave_pax` varchar(20) DEFAULT NULL,
  `nombre_pax` varchar(30) DEFAULT NULL,
  `fecha_recoge` date DEFAULT NULL,
  `fecha_entrega` date DEFAULT NULL,
  `fecha_emision` date DEFAULT NULL,
  `fecha_solicitud` date DEFAULT NULL,
  `numero_dias` smallint(6) DEFAULT NULL,
  `tipo_auto` char(4) DEFAULT NULL,
  `numero_autos` int(11) DEFAULT NULL,
  `cve_moneda` char(3) DEFAULT NULL,
  `tarifa_facturada` decimal(18,6) DEFAULT NULL,
  `tarifa_regular` decimal(18,6) DEFAULT NULL,
  `tarifa_ofrecida` decimal(18,6) DEFAULT NULL,
  `tarifa_diaria` decimal(18,6) DEFAULT NULL,
  `tarifa_total` decimal(18,6) DEFAULT NULL,
  `impuesto` decimal(18,6) DEFAULT NULL,
  `comision` decimal(18,6) DEFAULT NULL,
  `tipo_cambio` decimal(16,4) DEFAULT NULL,
  `voucher` varchar(20) DEFAULT NULL,
  `forma_pago` char(2) DEFAULT NULL,
  `tarjeta` varchar(20) DEFAULT NULL,
  `cve_ciudad_renta` char(4) DEFAULT NULL,
  `nombre_ciudad_renta` varchar(30) DEFAULT NULL,
  `cp_recoge` varchar(20) DEFAULT NULL,
  `cp_entrega` varchar(20) DEFAULT NULL,
  `ciudad_recoge` varchar(100) DEFAULT NULL,
  `ciudad_entrega` varchar(100) DEFAULT NULL,
  `direccion_recoge` varchar(255) DEFAULT NULL,
  `direccion_entrega` varchar(255) DEFAULT NULL,
  `cancelacion` char(1) DEFAULT NULL,
  `fecha_mod` timestamp NULL DEFAULT NULL,
  `id_usuario` int(11) DEFAULT NULL,
  PRIMARY KEY (`id_gds_autos`),
  KEY `fk_autos_usuario_idx` (`id_usuario`),
  CONSTRAINT `fk_tr_autos_usuario` FOREIGN KEY (`id_usuario`) REFERENCES `suite_mig_conf`.`st_adm_tr_usuario` (`id_usuario`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=54 DEFAULT CHARSET=utf8;
