CREATE TABLE `st_adm_tr_empresa` (
  `id_empresa` int(11) NOT NULL AUTO_INCREMENT,
  `id_direccion` int(11) DEFAULT NULL,
  `id_base_datos` int(11) DEFAULT NULL,
  `id_idioma` int(11) NOT NULL,
  `cve_pais` char(2) DEFAULT NULL,
  `nom_empresa` varchar(100) DEFAULT NULL,
  `rfc_sucursal` varchar(45) DEFAULT NULL,
  `cve_empresa` varchar(45) DEFAULT NULL,
  `comercial_empresa` varchar(100) DEFAULT NULL,
  `razon_social` varchar(250) DEFAULT NULL,
  `email_empresa` varchar(60) DEFAULT NULL,
  `telefono_empresa` varchar(35) DEFAULT NULL,
  `matriz_empresa` varchar(45) DEFAULT NULL,
  `id_zona_horaria` int(11) DEFAULT NULL,
  `usuarios` int(11) DEFAULT NULL,
  `sucursales` int(11) DEFAULT NULL,
  `outsoursing` int(11) DEFAULT '0',
  `no_licencias_usuario` int(11) DEFAULT '0',
  `id_tipo_paquete` int(11) NOT NULL,
  `forma_pago_folios` enum('CREDITO','PREPAGO') DEFAULT 'PREPAGO',
  `estatus_empresa` tinyint(1) DEFAULT '1',
  `fecha_mod_empresa` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_empresa`),
  KEY `fk_st_adm_tr_empresa_st_adm_tc_direccion_idx` (`id_direccion`) USING BTREE,
  KEY `fk_st_adm_tr_empresa_base_idx` (`id_base_datos`) USING BTREE,
  KEY `fk_st_adm_tr_empresa_idioma_idx` (`id_idioma`) USING BTREE,
  KEY `fk_st_adm_tr_empresa_st_adm_tc_tipo_paquete_idx` (`id_tipo_paquete`),
  CONSTRAINT `fk_st_adm_tr_empresa_base` FOREIGN KEY (`id_base_datos`) REFERENCES `st_adm_tc_base_datos` (`id_base_datos`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_st_adm_tr_empresa_idioma` FOREIGN KEY (`id_idioma`) REFERENCES `st_adm_tc_idioma` (`id_idioma`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_st_adm_tr_empresa_st_adm_tc_direccion` FOREIGN KEY (`id_direccion`) REFERENCES `st_adm_tc_direccion` (`id_direccion`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_st_adm_tr_empresa_st_adm_tc_tipo_paquete` FOREIGN KEY (`id_tipo_paquete`) REFERENCES `st_adm_tc_tipo_paquete` (`id_tipo_paquete`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=36 DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;
