CREATE TABLE `ic_cat_tr_vendedor` (
  `id_vendedor` int(11) NOT NULL AUTO_INCREMENT,
  `id_grupo_empresa` int(11) NOT NULL,
  `id_sucursal` int(11) NOT NULL,
  `id_comision` int(11) DEFAULT NULL,
  `id_comision_aux` int(11) DEFAULT NULL,
  `clave` char(10) NOT NULL,
  `nombre` char(90) DEFAULT NULL,
  `email` varchar(250) DEFAULT NULL,
  `cve_gds_sa` varchar(10) DEFAULT NULL,
  `cve_gds_am` varchar(10) DEFAULT NULL,
  `cve_gds_ws` varchar(10) DEFAULT NULL,
  `cve_gds_ap` varchar(10) DEFAULT NULL,
  `id_usuario_vendedor` int(11) DEFAULT '0',
  `estatus` enum('ACTIVO','INACTIVO') DEFAULT 'ACTIVO',
  `fecha_mod` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `id_usuario` int(11) NOT NULL,
  PRIMARY KEY (`id_vendedor`),
  KEY `fk_vendedor_usuario_idx` (`id_usuario`),
  KEY `fk_ic_fac_tr_vendedor_ic_cat_tr_sucursal1_idx` (`id_sucursal`) USING BTREE,
  KEY `fk_vendor_comision_idx` (`id_comision`) USING BTREE,
  KEY `fk_vendedor_grupo_empresa_idx` (`id_grupo_empresa`) USING BTREE,
  CONSTRAINT `fk_ic_fac_tr_vendedor_ic_cat_tr_sucursal1` FOREIGN KEY (`id_sucursal`) REFERENCES `ic_cat_tr_sucursal` (`id_sucursal`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendedor_grupo_empresa` FOREIGN KEY (`id_grupo_empresa`) REFERENCES `suite_mig_conf`.`st_adm_tr_grupo_empresa` (`id_grupo_empresa`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendedor_usuario` FOREIGN KEY (`id_usuario`) REFERENCES `suite_mig_conf`.`st_adm_tr_usuario` (`id_usuario`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1695 DEFAULT CHARSET=utf8;
