CREATE TABLE `ic_cat_tr_serie` (
  `id_serie` int(11) NOT NULL AUTO_INCREMENT,
  `id_grupo_empresa` int(11) NOT NULL,
  `id_usuario_solicita` int(11) NOT NULL,
  `id_sucursal` int(11) NOT NULL,
  `id_formato` int(11) NOT NULL,
  `id_formato_concentrado` int(11) DEFAULT NULL,
  `id_moneda` int(11) DEFAULT NULL,
  `id_autorizado_por` int(11) DEFAULT NULL,
  `id_revisado_por` int(11) DEFAULT NULL,
  `cve_serie` char(5) NOT NULL,
  `cve_tipo_serie` char(4) NOT NULL,
  `cve_tipo_doc` char(4) DEFAULT NULL,
  `folio_serie` int(11) DEFAULT NULL,
  `descripcion_serie` varchar(50) DEFAULT NULL,
  `electronica_serie` char(1) DEFAULT NULL,
  `automatico_serie` int(11) DEFAULT '0',
  `tipo_requisicion` char(1) DEFAULT 'N',
  `factura_xcta_terceros` tinyint(1) DEFAULT NULL,
  `copias_serie` int(11) DEFAULT NULL,
  `no_max_ren_serie` int(11) DEFAULT NULL,
  `tipo_formato` char(2) DEFAULT NULL,
  `estatus_serie` enum('ACTIVO','INACTIVO') DEFAULT 'ACTIVO',
  `fecha_mod_serie` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `id_usuario` int(11) NOT NULL,
  PRIMARY KEY (`id_serie`),
  KEY `fk_ic_cat_tr_serie_ic_cat_tr_sucursal_idx` (`id_sucursal`) USING BTREE,
  KEY `fk_ic_cat_tr_serie_ic_cat__tc_formato_idx` (`id_formato`) USING BTREE,
  KEY `fk_ic_cat_tr_serie_ic_cat_tr_tipo_serie1_idx` (`cve_tipo_serie`) USING BTREE,
  KEY `fk_ic_cat_tr_serie_ic_cat_tr_tipo_doc1_idx` (`cve_tipo_doc`) USING BTREE,
  KEY `fk_serie_usuario_idx` (`id_usuario`) USING BTREE,
  KEY `fk_serie_grupo_empresa_idx` (`id_grupo_empresa`) USING BTREE,
  KEY `fk_serie_moneda_idx` (`id_moneda`) USING BTREE,
  CONSTRAINT `fk_ic_cat_tr_serie_ic_cat_tc_formato` FOREIGN KEY (`id_formato`) REFERENCES `ic_cat_tc_formato` (`id_formato`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_ic_cat_tr_serie_ic_cat_tr_sucursal` FOREIGN KEY (`id_sucursal`) REFERENCES `ic_cat_tr_sucursal` (`id_sucursal`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_ic_cat_tr_serie_ic_cat_tr_tipo_doc1` FOREIGN KEY (`cve_tipo_doc`) REFERENCES `ic_cat_tr_tipo_doc` (`cve_tipo_doc`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_ic_cat_tr_serie_ic_cat_tr_tipo_serie1` FOREIGN KEY (`cve_tipo_serie`) REFERENCES `ic_cat_tc_tipo_serie` (`cve_tipo_serie`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_serie_grupo_empresa` FOREIGN KEY (`id_grupo_empresa`) REFERENCES `suite_mig_conf`.`st_adm_tr_grupo_empresa` (`id_grupo_empresa`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_serie_moneda` FOREIGN KEY (`id_moneda`) REFERENCES `ct_glob_tc_moneda` (`id_moneda`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_serie_usuario` FOREIGN KEY (`id_usuario`) REFERENCES `suite_mig_conf`.`st_adm_tr_usuario` (`id_usuario`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=218 DEFAULT CHARSET=utf8;
