CREATE TABLE `ic_fac_tr_compras_x_servicio` (
  `id_compras_x_servicio` int(11) NOT NULL AUTO_INCREMENT,
  `id_grupo_empresa` int(11) DEFAULT NULL,
  `id_tc_corporativa` int(11) DEFAULT NULL,
  `id_factura` int(11) DEFAULT NULL,
  `id_proveedor` int(11) DEFAULT NULL,
  `id_moneda` int(11) DEFAULT NULL,
  `no_tarjeta_credito` char(45) DEFAULT NULL,
  `origen_compra` enum('FACTURACION','INTERFACE') DEFAULT NULL,
  `tipo_cambio` decimal(18,4) DEFAULT '0.0000',
  `importe` decimal(15,2) DEFAULT '0.00',
  `importe_moneda_base` decimal(15,2) DEFAULT '0.00',
  `importe_usd` decimal(15,2) DEFAULT '0.00',
  `importe_euros` decimal(15,2) DEFAULT '0.00',
  `propietario_tc` enum('T.C. CLIENTE','CORPORATIVA','NO APLICA') DEFAULT NULL,
  `importe_tc` decimal(15,2) DEFAULT '0.00',
  `importe_moneda_base_tc` decimal(15,2) DEFAULT '0.00',
  `importe_usd_tc` decimal(15,2) DEFAULT '0.00',
  `importe_euros_tc` decimal(15,2) DEFAULT '0.00',
  `forma_pago_prov_efectivo` enum('CREDITO PROVEEDOR','CONTADO','NO APLICA') DEFAULT NULL,
  `importe_efectivo` decimal(15,2) DEFAULT '0.00',
  `importe_moneda_base_efectivo` decimal(15,2) DEFAULT '0.00',
  `importe_usd_2` decimal(15,2) DEFAULT '0.00',
  `importe_euros_2` decimal(15,2) DEFAULT '0.00',
  `referencia` char(20) DEFAULT NULL,
  `fecha_cargo` date DEFAULT NULL,
  `fecha_corte` date DEFAULT NULL,
  `fecha_vencimiento` date DEFAULT NULL,
  `estatus` enum('ACTIVO','CANCELADO') DEFAULT 'ACTIVO',
  `fecha_mod` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_compras_x_servicio`)
) ENGINE=InnoDB AUTO_INCREMENT=630 DEFAULT CHARSET=latin1;
