CREATE TABLE `ic_glob_tr_cxp` (
  `id_cxp` int(11) NOT NULL AUTO_INCREMENT,
  `id_grupo_empresa` int(11) NOT NULL,
  `id_sucursal` int(11) NOT NULL,
  `id_serie` int(11) NOT NULL,
  `numero` int(13) DEFAULT NULL,
  `fecha_captura` date NOT NULL,
  `id_proveedor` int(11) NOT NULL,
  `serie_factura` char(25) NOT NULL,
  `numero_factura` char(15) NOT NULL,
  `fecha_factura` date NOT NULL,
  `origen` enum('GASTO','VENTA') NOT NULL,
  `id_grupo_fit` int(11) DEFAULT NULL,
  `id_moneda` int(11) NOT NULL,
  `tipo_cambio` decimal(15,4) DEFAULT '1.0000',
  `importe_total` decimal(16,2) NOT NULL DEFAULT '0.00',
  `pagos_total` decimal(16,2) DEFAULT '0.00',
  `saldo_total` decimal(16,2) DEFAULT '0.00',
  `importe_mn` decimal(16,2) NOT NULL DEFAULT '0.00',
  `pagos_mn` decimal(16,2) DEFAULT '0.00',
  `saldo_mn` decimal(16,2) DEFAULT '0.00',
  `importe_usd` decimal(17,4) DEFAULT '0.0000',
  `tipo_cambio_usd` decimal(15,4) DEFAULT '0.0000',
  `importe_eur` decimal(17,4) DEFAULT '0.0000',
  `tipo_cambio_eur` decimal(15,4) DEFAULT '0.0000',
  `forma_pago` char(1) DEFAULT NULL,
  `id_concepto_pago` int(11) DEFAULT NULL,
  `id_categoria_concepto` int(11) DEFAULT NULL,
  `descripcion` text,
  `estatus` enum('ACTIVO','CANCELADO') DEFAULT 'ACTIVO',
  `situacion` enum('PENDIENTE','PAGADO','PROGRAMADO','PAGOPARCIAL') DEFAULT 'PENDIENTE',
  `solicito` varchar(255) DEFAULT NULL,
  `cancelado` int(11) NOT NULL DEFAULT '0',
  `id_motivo_cancelacion` int(11) DEFAULT NULL,
  `observaciones_cancelacion` text,
  `fecha_cancelacion` date DEFAULT NULL,
  `hora_cancelacion` time DEFAULT NULL,
  `id_usuario_cancelacion` int(11) DEFAULT NULL,
  `fecha_mod` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `id_usuario` int(11) DEFAULT NULL,
  PRIMARY KEY (`id_cxp`),
  KEY `fk_cxp_grupo_empresa_idx` (`id_grupo_empresa`),
  KEY `fk_cxp_sucursal_idx` (`id_sucursal`),
  KEY `fk_cxp_proveedor_idx` (`id_proveedor`),
  KEY `fk_cxp_moneda_idx` (`id_moneda`),
  KEY `fk_cxp_usuario_mod_idx` (`id_usuario`),
  KEY `fk_cxp_serie_idx` (`id_serie`),
  KEY `fk_cxp_grupo_fir_idx` (`id_grupo_fit`),
  KEY `fk_cxp_grupo_fit_idx` (`id_grupo_fit`),
  KEY `fk_cxp_usuario_cancelacion_cxc_idx` (`id_usuario_cancelacion`),
  CONSTRAINT `fk_cxp_grupo_empresa` FOREIGN KEY (`id_grupo_empresa`) REFERENCES `suite_mig_conf`.`st_adm_tr_grupo_empresa` (`id_grupo_empresa`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_cxp_grupo_fit` FOREIGN KEY (`id_grupo_fit`) REFERENCES `ic_fac_tc_grupo_fit` (`id_grupo_fit`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_cxp_moneda` FOREIGN KEY (`id_moneda`) REFERENCES `ct_glob_tc_moneda` (`id_moneda`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_cxp_proveedor` FOREIGN KEY (`id_proveedor`) REFERENCES `ic_cat_tr_proveedor` (`id_proveedor`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_cxp_serie` FOREIGN KEY (`id_serie`) REFERENCES `ic_cat_tr_serie` (`id_serie`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_cxp_sucursal` FOREIGN KEY (`id_sucursal`) REFERENCES `ic_cat_tr_sucursal` (`id_sucursal`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_cxp_usuario_cancelacion` FOREIGN KEY (`id_usuario_cancelacion`) REFERENCES `suite_mig_conf`.`st_adm_tr_usuario` (`id_usuario`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_cxp_usuario_mod` FOREIGN KEY (`id_usuario`) REFERENCES `suite_mig_conf`.`st_adm_tr_usuario` (`id_usuario`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=343 DEFAULT CHARSET=latin1;
