CREATE TABLE `ic_gds_tr_vuelos` (
  `id_gds_vuelos` int(11) NOT NULL AUTO_INCREMENT,
  `id_boleto` int(11) DEFAULT NULL,
  `id_factura_detalle` int(11) DEFAULT NULL,
  `id_gds_general` int(11) DEFAULT NULL,
  `clave_linea_aerea` char(3) DEFAULT NULL,
  `clave_reservacion` varchar(20) DEFAULT NULL,
  `clave_pax` varchar(20) DEFAULT NULL,
  `nombre_pax` varchar(30) DEFAULT NULL,
  `ruta` varchar(100) DEFAULT NULL,
  `tarifa_facturada` decimal(15,2) DEFAULT NULL,
  `impuesto1` decimal(15,2) DEFAULT NULL,
  `impuesto2` decimal(15,2) DEFAULT NULL,
  `impuesto3` decimal(15,2) DEFAULT NULL,
  `tarifa_regular` decimal(15,2) DEFAULT NULL,
  `tarifa_ofrecida` decimal(15,2) DEFAULT NULL,
  `clases` varchar(20) DEFAULT NULL,
  `clase_principal` char(1) DEFAULT NULL,
  `clase_alta` char(1) DEFAULT NULL,
  `clase_baja` char(1) DEFAULT NULL,
  `codigo_razon` varchar(10) DEFAULT NULL,
  `origen` char(4) DEFAULT NULL,
  `destino_principal` char(4) DEFAULT NULL,
  `fecha_regreso` date DEFAULT NULL,
  `hora_regreso` varchar(5) DEFAULT NULL,
  `fecha_salida` date DEFAULT NULL,
  `hora_salida` varchar(5) DEFAULT NULL,
  `fecha_emision` date DEFAULT NULL,
  `fecha_solicitud` date DEFAULT NULL,
  `serie` char(5) DEFAULT NULL,
  `fac_numero` int(11) DEFAULT NULL,
  `forma_pago` char(2) DEFAULT NULL,
  `tarjeta` varchar(20) DEFAULT NULL,
  `comision` decimal(18,6) DEFAULT NULL,
  `codigo_razon_realizado` varchar(100) DEFAULT NULL,
  `codigo_razon_rechazo` varchar(100) DEFAULT NULL,
  `boleto_conjunto` text,
  `boleto_contra` text,
  `boleto_cancelado` char(1) DEFAULT NULL,
  `boleto_revisado` varchar(15) DEFAULT NULL,
  `boleto_lowcost` varchar(15) DEFAULT NULL,
  `tour_code` varchar(25) DEFAULT NULL,
  `intdom` enum('NACIONAL','INTERNACIONAL') DEFAULT NULL,
  `electronico` char(1) DEFAULT NULL,
  `conjunto` char(1) DEFAULT NULL,
  `numero_boleto_conjunto` int(11) DEFAULT NULL,
  `iata` varchar(9) DEFAULT NULL,
  `tc_propietario` enum('AGENCIA','CLIENTE') DEFAULT NULL,
  `fecha_mod` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `id_usuario` int(11) DEFAULT NULL,
  PRIMARY KEY (`id_gds_vuelos`),
  KEY `fk_vuelos_usuario_idx` (`id_usuario`),
  CONSTRAINT `fk_vuelos_usuario` FOREIGN KEY (`id_usuario`) REFERENCES `suite_mig_conf`.`st_adm_tr_usuario` (`id_usuario`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=5415 DEFAULT CHARSET=utf8;
