CREATE TABLE `ic_gds_tr_hoteles` (
  `id_gds_hoteles` int(11) NOT NULL AUTO_INCREMENT,
  `id_factura_detalle` int(11) DEFAULT NULL,
  `id_boleto` int(11) DEFAULT NULL,
  `id_gds_general` int(11) DEFAULT NULL,
  `proveedor` varchar(10) DEFAULT NULL,
  `clave_reserva` varchar(20) DEFAULT NULL,
  `clave_confirmacion` varchar(20) DEFAULT NULL,
  `clave_pax` varchar(20) DEFAULT NULL,
  `fecha_entrada` date DEFAULT NULL,
  `fecha_salida` date DEFAULT NULL,
  `fecha_emision` date DEFAULT NULL,
  `fecha_solicitud` date DEFAULT NULL,
  `cadena` int(11) DEFAULT NULL,
  `propiedad` char(6) DEFAULT NULL,
  `hotel_nombre` varchar(100) DEFAULT NULL,
  `numero_noches` smallint(6) DEFAULT NULL,
  `numero_hab` int(11) DEFAULT NULL,
  `cve_habitacion` char(4) DEFAULT NULL,
  `tipo_habitacion` char(4) DEFAULT NULL,
  `costo_hab_noche` decimal(18,6) DEFAULT NULL,
  `ciudad` varchar(20) DEFAULT NULL,
  `codigo_postal` varchar(20) DEFAULT NULL,
  `direccion` varchar(100) DEFAULT NULL,
  `telefono` varchar(20) DEFAULT NULL,
  `poblacion` varchar(50) DEFAULT NULL,
  `cve_moneda` char(3) DEFAULT NULL,
  `tipo_cambio` decimal(16,4) DEFAULT NULL,
  `tarifa_facturada` decimal(18,6) DEFAULT NULL,
  `tarifa_regular` decimal(18,6) DEFAULT NULL,
  `tarifa_ofrecida` decimal(18,6) DEFAULT NULL,
  `tarifa_total_noches` decimal(18,6) DEFAULT NULL,
  `tarifa_neta` decimal(18,6) DEFAULT NULL,
  `impuesto1` decimal(18,6) DEFAULT NULL,
  `impuesto2` decimal(18,6) DEFAULT NULL,
  `comision` decimal(18,6) DEFAULT NULL,
  `forma_pago` char(2) DEFAULT NULL,
  `tarjeta` varchar(20) DEFAULT NULL,
  `voucher` varchar(20) DEFAULT NULL,
  `cancelado` char(1) DEFAULT NULL,
  `fecha_mod` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `id_usuario` int(11) DEFAULT NULL,
  PRIMARY KEY (`id_gds_hoteles`),
  KEY `fk_hoteles_usuario_idx` (`id_usuario`),
  CONSTRAINT `fk_hoteles_usuario` FOREIGN KEY (`id_usuario`) REFERENCES `suite_mig_conf`.`st_adm_tr_usuario` (`id_usuario`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=401 DEFAULT CHARSET=utf8;
