CREATE TABLE `temp` (
  `slno` int(11) NOT NULL AUTO_INCREMENT,
  `debit` int(11) DEFAULT NULL,
  `credit` int(11) DEFAULT NULL,
  PRIMARY KEY (`slno`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;
