CREATE TABLE `st_adm_tr_empresa_reservaciones` (
  `id_empresa_reservaciones` int(11) NOT NULL AUTO_INCREMENT,
  `id_empresa` int(11) DEFAULT NULL,
  `base_url` varchar(100) DEFAULT NULL,
  `application` varchar(20) DEFAULT NULL,
  `username` varchar(20) DEFAULT NULL,
  `password` varchar(30) DEFAULT NULL,
  `xclient` varchar(20) DEFAULT NULL,
  `service_type` varchar(5) DEFAULT NULL,
  `tipo_documento` enum('FACT','DOCS','NC','DC') DEFAULT 'FACT',
  `serie` char(5) DEFAULT NULL,
  `formato` char(1) DEFAULT 'A',
  `moneda` char(3) DEFAULT 'MXN',
  `tipo_producto` int(11) DEFAULT '0',
  `producto_sat` varchar(8) DEFAULT '90121502',
  `unidad_medida` int(11) DEFAULT '0',
  `proveedor_aereo` int(11) DEFAULT '0',
  `servicio_aereo` int(11) DEFAULT '0',
  `metodo_pago` enum('PPD','PUE') DEFAULT 'PUE',
  `id_usuario` int(11) DEFAULT NULL,
  `fecha_mod` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id_empresa_reservaciones`),
  KEY `fk_empresa_reservaciones_empresa_idx` (`id_empresa`),
  CONSTRAINT `fk_empresa_reservaciones_empresa` FOREIGN KEY (`id_empresa`) REFERENCES `st_adm_tr_empresa` (`id_empresa`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;
