CREATE TABLE `st_adm_tr_config_admin` (
  `id_config_admin` int(11) NOT NULL AUTO_INCREMENT,
  `id_empresa` int(11) NOT NULL,
  `inventario_bol_linea` char(1) CHARACTER SET latin1 NOT NULL DEFAULT 'N',
  `notas_factura` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `unidad_negocio_obli` char(1) CHARACTER SET latin1 DEFAULT 'N',
  `origen_venta_obli` char(1) CHARACTER SET latin1 DEFAULT 'N',
  `cambios_clie_fijo` char(1) CHARACTER SET latin1 DEFAULT 'N',
  `cambios_doc_serv` char(1) CHARACTER SET latin1 DEFAULT 'N',
  `cambios_factura` char(1) CHARACTER SET latin1 DEFAULT 'N',
  `desglose_impuesto` char(1) CHARACTER SET latin1 DEFAULT 'N',
  `tipo_descu` char(1) CHARACTER SET latin1 NOT NULL DEFAULT '1',
  `limite_credito` char(1) CHARACTER SET latin1 DEFAULT '3',
  `ant_cl` char(1) CHARACTER SET latin1 DEFAULT '1',
  `multi_formato_imp` char(1) CHARACTER SET latin1 DEFAULT 'N',
  `nc_fac_no_exist` char(1) CHARACTER SET latin1 DEFAULT 'N',
  `nc_cambios` char(1) CHARACTER SET latin1 DEFAULT 'N',
  `nc_valida_fac` char(1) CHARACTER SET latin1 DEFAULT 'S',
  `cxcdven1` tinyint(4) DEFAULT '7',
  `cxcdven2` tinyint(4) DEFAULT '14',
  `cxcdven3` tinyint(4) DEFAULT '21',
  `cxcdven4` tinyint(4) DEFAULT '28',
  `cxcdven5` tinyint(4) DEFAULT '0',
  `cxcdven6` tinyint(4) DEFAULT '0',
  `cxpdven1` tinyint(4) DEFAULT '7',
  `cxpdven2` tinyint(4) DEFAULT '14',
  `cxpdven3` tinyint(4) DEFAULT '21',
  `cxpdven4` tinyint(4) DEFAULT '28',
  `cxpdven5` tinyint(4) DEFAULT NULL,
  `cxpdven6` tinyint(4) DEFAULT NULL,
  `enviar_bol_elect` char(1) CHARACTER SET latin1 NOT NULL DEFAULT 'N',
  `incluir_bol` char(1) CHARACTER SET latin1 DEFAULT 'N',
  `incluir_pax` char(1) CHARACTER SET latin1 DEFAULT 'N',
  `incluir_pnr` char(1) CHARACTER SET latin1 DEFAULT 'N',
  `incluir_fecha_viaje` char(1) CHARACTER SET latin1 DEFAULT 'N',
  `calculo_markup` char(1) CHARACTER SET latin1 DEFAULT 'M',
  `logo_empresa` varchar(500) CHARACTER SET latin1 DEFAULT NULL,
  `aviso_no_folios` int(11) DEFAULT '0',
  `forma_pago_folios` enum('CREDITO','PREPAGO') DEFAULT 'PREPAGO',
  `credito_folios_estatus` enum('ACTIVO','INACTIVO') DEFAULT 'ACTIVO',
  `centro_costos_obli` char(1) DEFAULT 'N',
  `estatus` enum('ACTIVO','INACTIVO') CHARACTER SET latin1 DEFAULT 'ACTIVO',
  `fecha_mod` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `id_usuario` int(11) NOT NULL,
  PRIMARY KEY (`id_config_admin`),
  UNIQUE KEY `id_empresa_UNIQUE` (`id_empresa`) USING BTREE,
  KEY `fk_usuario_idx` (`id_usuario`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=59 DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;
